/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Day = IDL.Nat;
export const DayProgress = IDL.Vec(IDL.Bool);
export const AllProgress = IDL.Vec(IDL.Tuple(Day, DayProgress));
export const CommunityUserStats = IDL.Record({
  'username' : IDL.Text,
  'overallCompletion' : IDL.Float64,
  'totalPoints' : IDL.Nat,
  'currentDay' : IDL.Nat,
  'currentStreak' : IDL.Nat,
  'todayCompletion' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'joinedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'getAllProgress' : IDL.Func([], [AllProgress], ['query']),
  'getCommunityStats' : IDL.Func([], [IDL.Vec(CommunityUserStats)], ['query']),
  'getCurrentDay' : IDL.Func([], [IDL.Nat], ['query']),
  'getDailyRandomChallenge' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getDayProgress' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(IDL.Bool))],
      ['query'],
    ),
  'getMyAnalytics' : IDL.Func([], [AllProgress], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalPoints' : IDL.Func([], [IDL.Nat], ['query']),
  'nextDay' : IDL.Func([], [], []),
  'resetProgress' : IDL.Func([], [], []),
  'setChallenge' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
  'setUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Day = IDL.Nat;
  const DayProgress = IDL.Vec(IDL.Bool);
  const AllProgress = IDL.Vec(IDL.Tuple(Day, DayProgress));
  const CommunityUserStats = IDL.Record({
    'username' : IDL.Text,
    'overallCompletion' : IDL.Float64,
    'totalPoints' : IDL.Nat,
    'currentDay' : IDL.Nat,
    'currentStreak' : IDL.Nat,
    'todayCompletion' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'joinedAt' : IDL.Int,
  });
  
  return IDL.Service({
    'getAllProgress' : IDL.Func([], [AllProgress], ['query']),
    'getCommunityStats' : IDL.Func(
        [],
        [IDL.Vec(CommunityUserStats)],
        ['query'],
      ),
    'getCurrentDay' : IDL.Func([], [IDL.Nat], ['query']),
    'getDailyRandomChallenge' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getDayProgress' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(IDL.Bool))],
        ['query'],
      ),
    'getMyAnalytics' : IDL.Func([], [AllProgress], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalPoints' : IDL.Func([], [IDL.Nat], ['query']),
    'nextDay' : IDL.Func([], [], []),
    'resetProgress' : IDL.Func([], [], []),
    'setChallenge' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
    'setUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };