/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AllProgress = Array<[Day, DayProgress]>;
export interface CommunityUserStats {
  'username' : string,
  'overallCompletion' : number,
  'totalPoints' : bigint,
  'currentDay' : bigint,
  'currentStreak' : bigint,
  'todayCompletion' : number,
}
export type Day = bigint;
export type DayProgress = Array<boolean>;
export interface UserProfile { 'username' : string, 'joinedAt' : bigint }
export interface _SERVICE {
  'getAllProgress' : ActorMethod<[], AllProgress>,
  'getCommunityStats' : ActorMethod<[], Array<CommunityUserStats>>,
  'getCurrentDay' : ActorMethod<[], bigint>,
  'getDailyRandomChallenge' : ActorMethod<[], Array<string>>,
  'getDayProgress' : ActorMethod<[bigint], [] | [Array<boolean>]>,
  'getMyAnalytics' : ActorMethod<[], AllProgress>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getStreak' : ActorMethod<[], bigint>,
  'getTotalPoints' : ActorMethod<[], bigint>,
  'nextDay' : ActorMethod<[], undefined>,
  'resetProgress' : ActorMethod<[], undefined>,
  'setChallenge' : ActorMethod<[bigint, bigint, boolean], undefined>,
  'setUsername' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];